### ISSUE TITLE
Parallel testing fails with Docker

### ISSUE THREAD

**Issue by mikkonie** [bihealth/kiosc-server#152]
**Describe the bug**
The `--parallel` setting in `make test` fails with Docker, see an example error dump below. Basically, due to tests being run in parallel we end up potentially trying to run the command multiple times concurrently, resulting in errors.

To fix, the `--parallel` flag should be removed. The `test-no-docker` target works fine when run with the flag.

**To Reproduce**
1. Run `make test`
2. Observe the errors :)
3. If errors don't occur, restart the tests a few times and you should be able to see them

**Comment by mikkonie** [comment]
Examples of errors:

```
======================================================================
ERROR: test_delete_exited_mocked (containers.tests.test_tasks.TestContainerTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 679, in run
    self._callTearDown()
  File "/usr/lib/python3.8/unittest/case.py", line 636, in _callTearDown
    self.tearDown()
  File "/home/mikkopen/code/kiosc-server/containers/tests/test_tasks.py", line 55, in tearDown
    self.cli.prune_images()
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/image.py", line 351, in prune_images
    return self._result(self._post(url, params=params), True)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: None: None

======================================================================
ERROR: test_delete_initial_mocked (containers.tests.test_tasks.TestContainerTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 679, in run
    self._callTearDown()
  File "/usr/lib/python3.8/unittest/case.py", line 636, in _callTearDown
    self.tearDown()
  File "/home/mikkopen/code/kiosc-server/containers/tests/test_tasks.py", line 55, in tearDown
    self.cli.prune_images()
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/image.py", line 351, in prune_images
    return self._result(self._post(url, params=params), True)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/images/prune: Conflict ("a prune operation is already running")

======================================================================
ERROR: test_delete_running_mocked (containers.tests.test_tasks.TestContainerTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 679, in run
    self._callTearDown()
  File "/usr/lib/python3.8/unittest/case.py", line 636, in _callTearDown
    self.tearDown()
  File "/home/mikkopen/code/kiosc-server/containers/tests/test_tasks.py", line 55, in tearDown
    self.cli.prune_images()
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/image.py", line 351, in prune_images
    return self._result(self._post(url, params=params), True)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: None: None

======================================================================
ERROR: test_pause_mocked (containers.tests.test_tasks.TestContainerTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 679, in run
    self._callTearDown()
  File "/usr/lib/python3.8/unittest/case.py", line 636, in _callTearDown
    self.tearDown()
  File "/home/mikkopen/code/kiosc-server/containers/tests/test_tasks.py", line 55, in tearDown
    self.cli.prune_images()
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/image.py", line 351, in prune_images
    return self._result(self._post(url, params=params), True)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: None: None

======================================================================
ERROR: test_restart_mocked (containers.tests.test_tasks.TestContainerTask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 679, in run
    self._callTearDown()
  File "/usr/lib/python3.8/unittest/case.py", line 636, in _callTearDown
    self.tearDown()
  File "/home/mikkopen/code/kiosc-server/containers/tests/test_tasks.py", line 55, in tearDown
    self.cli.prune_images()
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/image.py", line 351, in prune_images
    return self._result(self._post(url, params=params), True)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/mikkopen/.virtualenvs/kiosc/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/images/prune: Conflict ("a prune operation is already running")
```
